micronaut:
  application:
    name: crawler-job-creator
  metrics:
    enabled: true
jobrunr:
  background-job-server:
    enabled: ${JOBRUNR_JOBS:false}
  dashboard:
    enabled: true
  job-scheduler:
    enabled: true
  jobs:
    retry-back-off-time-seed: 2
mongodb:
  servers.*.uuid-representation: STANDARD
  uri: mongodb://127.0.0.1:27017/jobrunr
endpoints:
  health:
    enabled: true
    details-visible: anonymous
  metrics:
    enabled: true
    sensitive: false


