micronaut:
  executors:
    consumer:
      type: fixed
      nThreads: 50
    producer:
      type: fixed
      nThreads: 50
  application:
    name: wikiDumpFileProcessor
kafka:
  key:
    serializer: org.apache.kafka.common.serialization.UUIDSerializer
    deserializer: org.apache.kafka.common.serialization.UUIDDeserializer
  value:
    serializer: io.confluent.kafka.serializers.protobuf.KafkaProtobufSerializer
    deserializer: io.confluent.kafka.serializers.protobuf.KafkaProtobufDeserializer
  enabled: true
  schema.registry.url: http://localhost:8081
