micronaut:
  application:
    name: wiki-downloader-request
kafka:
  enabled: true
  schema.registry.url: http://localhost:8081
  key:
    serializer: org.apache.kafka.common.serialization.UUIDSerializer
    deserializer: org.apache.kafka.common.serialization.UUIDDeserializer
  value:
    serializer: io.confluent.kafka.serializers.protobuf.KafkaProtobufSerializer
    deserializer: io.confluent.kafka.serializers.protobuf.KafkaProtobufDeserializer
wikipedia:
  dump-url: https://dumps.wikimedia.org/enwiki
  md5-url: ${wikipedia.dump-url}/20240120/
  download-location: /home/krickert/wikidata
  download-name: "${wikipedia.download-location}/wikiList.md5"
  fresh-copy: true
  attempt-latest: true # if true, will always try the latest version, regardless of attempt-load is set
  attempt-load: 20240120 # if set, attempt-latest should be false and it will load this specific version
