version: '3'
services:
  solr:
    image: solr:7.7.3-slim
    ports:
      - "8980:8983"
    networks: [search7]
    environment:
      ZK_HOST: "zoo:2181"
    depends_on: [zoo1]

  zoo1:
    image: zookeeper:3.4.14
    networks: [search7]
    container_name: zoo7
    hostname: zoo
    ports:
      - 2180:2181
    environment:
      ZOO_4LW_COMMANDS_WHITELIST: "mntr,conf,ruok"

networks:
  search7:
    driver: bridge