micronaut:
  server:
    port: 60401
  application:
    name: vectorizer
grpc:
  server:
    port: 50401
endpoints:
  health:
    enabled: true
    sensitive: false
vectorizer:
  model:
    url: "djl://ai.djl.huggingface.pytorch/sentence-transformers/all-MiniLM-L12-v2"
