micronaut:
  server:
    port: 60401
  application:
    name: vectorizer
consul:
  client:
    defaultZone: ${CONSUL_HOST:localhost}:${CONSUL_PORT:8500}
    registration:
      enabled: true
grpc:
  server:
    port: 50401
endpoints:
  health:
    enabled: true
    sensitive: false