endpoints:
  all:
    enabled: false
    sensitive: false
  loggers:
    write-sensitive: false
  health:
    details-visible: ANONYMOUS
    discovery-client:
      enabled: false
consul:
  client:
    registration:
      enabled: false
      check:
        enabled: false
    discovery:
      enabled: false
    pool:
      enabled: false