container-image:
  vectorizer:
    name: krickert/vectorizer:1.0-SNAPSHOT
    ports:
      grpc:
        internal: 50401
        mapped: ${random.port}
      rest:
        internal: 60401
        mapped: ${random.port}
  chunker:
    name: krickert/vectorizer:1.0-SNAPSHOT
    ports:
      grpc:
        internal: 50403
        mapped: ${random.port}
      rest:
        internal: 60403
        mapped: ${random.port}
