micronaut:
  jackson:
    json-view:
      enabled: true
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        mapping: /swagger-ui/**
        paths: classpath:META-INF/swagger/views/swagger-ui
  application:
    name: search-api
  openapi:
    property:
      naming:
        strategy: KEBAB_CASE
  server:
    port: 60410

solr:
  host: http://localhost:8983/solr