name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Set up JDK 17 and authenticate with Maven
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          server-id: github # Value of the id field of the <server> element in the settings.xml
          server-username: ${{ github.actor }} # Use the automatic GITHUB_ACTOR instead of secrets
          server-password: ${{ secrets.GH_PAT }}
          cache: maven

      - name: Build with Maven
        run: mvn -B package deploy --file pom.xml